package com.tbbstu.easyExcelTest.settings.mapper;

import com.tbbstu.easyExcelTest.settings.domain.Class;
import com.tbbstu.easyExcelTest.settings.domain.College;
import org.apache.ibatis.annotations.Param;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insertSelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    Class selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKeySelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKey(Class record);
    Class getClassByName(@Param("Name") String Name);
    Class getClassById(@Param("id") String id);


}