package com.tbbstu.easyExcelTest.settings.mapper;

import com.tbbstu.easyExcelTest.settings.domain.Class;
import com.tbbstu.easyExcelTest.settings.domain.College;
import com.tbbstu.easyExcelTest.settings.domain.Major;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;

public interface CollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    College selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKey(College record);

    College getCollegeByName(@Param("Name") String Name);
    College getCollegeById(@Param("id") String id);

}