package com.tbbstu.easyExcelTest.settings.mapper;

import com.tbbstu.easyExcelTest.settings.domain.Class;
import com.tbbstu.easyExcelTest.settings.domain.Major;
import org.apache.ibatis.annotations.Param;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    Major selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    int updateByPrimaryKey(Major record);

    Major getMajorByName(@Param("Name") String Name);
    Major getMajorgeById(@Param("id") String id);

}