package com.tbbstu.easyExcelTest.settings.domain;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}