package com.tbbstu.easyExcelTest.settings.domain;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.college_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.identity_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.report_time
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.image
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.state
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major_id
     *
     * @return the value of student.major_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major_id
     *
     * @param majorId the value for student.major_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.college_id
     *
     * @return the value of student.college_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.college_id
     *
     * @param collegeId the value for student.college_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.identity_id
     *
     * @return the value of student.identity_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.identity_id
     *
     * @param identityId the value for student.identity_id
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.report_time
     *
     * @return the value of student.report_time
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.report_time
     *
     * @param reportTime the value for student.report_time
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setReportTime(String reportTime) {
        this.reportTime = reportTime == null ? null : reportTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.image
     *
     * @return the value of student.image
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.image
     *
     * @param image the value for student.image
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.state
     *
     * @return the value of student.state
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.state
     *
     * @param state the value for student.state
     *
     * @mbggenerated Fri May 27 16:01:41 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "id='" + id + '\'' +
                ", classId='" + classId + '\'' +
                ", majorId='" + majorId + '\'' +
                ", collegeId='" + collegeId + '\'' +
                ", identityId='" + identityId + '\'' +
                ", reportTime='" + reportTime + '\'' +
                ", image='" + image + '\'' +
                ", state='" + state + '\'' +
                '}';
    }
}